# Generated by Django 3.0.7 on 2020-10-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_no', models.AutoField(primary_key=True, serialize=False)),
                ('poster_img', models.URLField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=50)),
                ('star_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('openning_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_viewers', models.IntegerField(default=0)),
                ('country_of_manufacture', models.CharField(default='', max_length=30)),
                ('movie_rateing', models.CharField(default='', max_length=30)),
                ('running_time', models.IntegerField(default=0)),
                ('summary', models.TextField(default='', max_length=300)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('movie_genre_no', models.AutoField(primary_key=True, serialize=False)),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Genre')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie')),
            ],
            options={
                'db_table': 'movies_genres',
            },
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('movie_director_no', models.AutoField(primary_key=True, serialize=False)),
                ('director_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Director')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie')),
            ],
            options={
                'db_table': 'movies_directors',
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('movie_actor_no', models.AutoField(primary_key=True, serialize=False)),
                ('actor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Actor')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie')),
            ],
            options={
                'db_table': 'movies_actors',
            },
        ),
        migrations.AddField(
            model_name='genre',
            name='to_Movie',
            field=models.ManyToManyField(through='movie.MovieGenre', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='director',
            name='to_movie',
            field=models.ManyToManyField(through='movie.MovieDirector', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='to_Movie',
            field=models.ManyToManyField(through='movie.MovieActor', to='movie.Movie'),
        ),
    ]
