# Generated by Django 3.0.7 on 2020-10-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desc_text',
            new_name='introduction',
        ),
    ]
