# Generated by Django 3.0.7 on 2020-10-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
    ]
