# Generated by Django 3.0.7 on 2020-10-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201018_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='openning_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
