# Generated by Django 3.0.7 on 2020-10-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201018_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='to_Movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Genre'),
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
