# Generated by Django 3.0.7 on 2020-10-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201018_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genre_id',
        ),
    ]
