# Generated by Django 3.0.7 on 2020-10-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201018_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(default='', max_length=300),
        ),
    ]
