# Generated by Django 3.0.7 on 2020-10-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20201018_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_rateing',
            new_name='movie_rating',
        ),
    ]
