# Generated by Django 3.0.7 on 2020-10-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20201018_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('movie_rating_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.MovieRating'),
        ),
    ]
