# Generated by Django 3.0.7 on 2020-10-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20201018_1906'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movierating',
            table='movie_ratings',
        ),
    ]
